### ISSUE TITLE
Renaming files fails

### ISSUE THREAD

**Issue by Q2114** [bridge-core/editor#580]
Hello, I found 2 bugs. 
 -1:
Bug with folder/file renaming. Bridge does not save the changed file/folder name. Video below ↓
https://youtube.com/shorts/r8RG4dvrJMM?feature=share

-2:
The bug is that the bridge cannot delete files from the modification. Video also below ↓
https://youtu.be/jAxyQ9Ok54U

-   OS: [WEB Chrome / Android 11]
-   App Version: [2.3.1]

**Comment by solvedDev** [comment]
I cannot reproduce the second error but maybe that one was already fixed by the commit fixing #573

**Comment by solvedDev** [comment]
Thanks for the great bug report (including the videos) btw! That was extremely helpful :)

**Comment by Q2114** [comment]
The bugs remain... Video below ↓
https://youtu.be/ae3842NZbYE
===========================
Chrome browser version:
![IMG_20220823_142427](https://user-images.githubusercontent.com/102694456/186146487-fa9f370a-2dbe-48a8-a6aa-8f9b73abea3d.jpg)

**Comment by solvedDev** [comment]
We did not roll out a new update yet.

**Comment by Q2114** [comment]
Oh, I'm sorry...  XD

**Comment by Q2114** [comment]
Thanks for the app :)

**Comment by solvedDev** [comment]
Np, v2.3.2 is rolling out now.

**Comment by Q2114** [comment]
Ok, I'll wait :3

**Comment by Q2114** [comment]
Greetings, there is no more bug with deleting files!
  But the bug with renaming files remained. Bridge never renames files. Video : https://youtu.be/gE3ObJs09gE
*Thanks*

**Comment by solvedDev** [comment]
We fixed a few issues with our file system with v2.3.5. Can you take a look at whether your issue is fixed now?

**Comment by Q2114** [comment]
Good evening. Yes, I took a video. But the file renaming error remained, maybe it's a problem with my smartphone...? I don't even know ._."

https://youtu.be/QkSFvNFJsOI

**Comment by solvedDev** [comment]
Thank you!

@Joelant05 I cannot reproduce this issue on my phone, can you try reproducing it when you find the time?

**Comment by solvedDev** [comment]
Small bump @Joelant05

**Comment by Joelant05** [comment]
Yeah sure. I completely missed this, will take a look now

**Comment by Joelant05** [comment]
I can reproduce the issue, it may be related to the issue we had with the tree editor inputs, since the keyboard shows "Next" instead of the regular enter button. Clicking off instead of pressing "Next" has the same issue also.

![Screenshot_20221204-164308_Chrome.jpg](https://user-images.githubusercontent.com/64587014/205503988-005a3621-9eee-4451-8190-1fcae6736da0.jpg)

**Comment by solvedDev** [comment]
Oh, that's a good catch. Thanks a lot! Let me hack together a PR real quick :D
